server:
  port: 9000
spring:
  application:
    name: ek-invoke
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com.netflix: DEBUG